services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    networks:
      default: {}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
      # MYSQL_DATABASE: '${DB_DATABASE}'
      # MYSQL_USER: '${DB_USERNAME}'
      # MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mariadb-data:/var/lib/mysql'
  phpmyadmin:
    image: 'phpmyadmin:fpm-alpine'
    restart: always
    # ports:
    #   - 8080:80
    networks:
      default: {}
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - UPLOAD_LIMIT=150M
    volumes:
      - phpmyadmin_data:/var/www/html/
      - ./info.php:/var/www/html/info.php
    depends_on:
      - mariadb
  nginx:
    image: nginx:stable-alpine-slim
    networks: 
      default: {}
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - phpmyadmin_data:/var/www/html:ro
      # - ./info.php:/var/www/html/info.php
    ports:
      - 8080:80
    depends_on:
      - mariadb
      - phpmyadmin
networks:
  default:
    name: database
    attachable: true
    external: true
volumes:
  mariadb-data: 
    driver: local
  phpmyadmin_data:
